export const CurrenciesOptions = [
  {value: "USD", label: "USD - Dólares estadounidenses"},
  {value: "EUR", label: "EUR - Euros"},
  {value: "ARS", label: "ARS - Pesos argentinos (dolar oficial)"},
  {value: "ARSBL", label: "ARS - Pesos argentinos (dolar blue)"},
  {value: "BOB", label: "BOB - Pesos bolivianos"},
  {value: "BRL", label: "BRL - Reales brasileros"},
  {value: "CLP", label: "CLP - Pesos chilenos"},
  {value: "COP", label: "COP - Pesos colombiano"},
  {value: "CUP", label: "CUP - Pesos cubanos"},
  {value: "GBP", label: "GBP - Libras esterlinas"},
  {value: "JPY", label: "JPY - Yenes japoneses"},
  {value: "MXN", label: "MXN - Pesos mexicanos"},
  {value: "PEN", label: "PEN - Soles peruanos"},
  {value: "PYG", label: "PYG - Guaranis paraguayos"},
  {value: "UYU", label: "UYU - Pesos uruguayos"},
]
